<?php
/**
 * @file
 * thuli_core_features.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function thuli_core_features_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Manaparai',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '09DED5B4-7073-4456-8F5B-36C897797BFB',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Arani',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '190B1306-94BF-4C6D-9DB0-0D6F959CE447',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Kallakuruchi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2090B193-2FB3-480D-970B-FEB8EC2A30DF',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Dharapuram',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '27B42E08-59F0-4D32-BFD1-D8995C4793E6',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Arakonam',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '29BA335C-CF67-4BD5-BDF1-FBD75F681640',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Bodinayakanur',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2C3E377F-7809-40F8-BC42-754E21721EF4',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Thoothukudi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '300453B8-44D0-4909-B568-180E3AA71921',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Aranthangi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '44B7A905-E1A2-480C-8FBC-D973921D4FA5',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Sivagangai',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '51FC3059-FB85-49C2-863D-E36161D4E22C',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Panruti',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '55D3488D-14B6-45F1-8E8F-BF9739947EDF',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Paramakudi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5DAD1A92-F8D2-48F9-BCD4-DBFA4FA9B48E',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Virudachalam',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '64D6671B-D912-4E49-A916-56A71A6B98CE',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Idappadi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6BE6D739-FE98-4C3F-8C76-2DC11002906D',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Sathiamangalam',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6CA78317-1F34-4995-9CC8-7F62CFB23F25',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Tenkasi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6E5EE399-BE20-4BE1-B067-4441E8977A9A',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Salem',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7152A08C-2F22-46FE-A044-4527119981A5',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Arcot',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '85D92C0E-013D-4F1F-952D-BECE7B84033F',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Chenglepet',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '875A0CFA-D16D-4099-A415-7A1E1CB053AE',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Tirunelveli',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '87895EF9-9E2F-41AE-AF03-FAA17FC4502E',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Kadayanallur',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8FE2A75A-2C86-4F2A-BE88-3560E3E7847D',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Aruppukottai',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9129CB09-8861-48BB-9F0C-7E05E6F3CA4E',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Cumbum',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '963C8F4B-92BC-4504-AB95-2E8A7823DEA3',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Tiruchirapalli',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9C58BA34-BC4B-4A30-A6B7-E5E2D0A5F4F9',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Erode',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9F346DD2-D228-4E61-A13D-9518B7C88B1D',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Thiruthangal',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'A01CF023-EFF0-40E5-94C5-E7B218542573',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Sankarankoil',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'A132130E-0260-429D-8F4D-239E5246F998',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Ramanathapuram',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'A724741F-B0B4-4D48-9E06-8A515900204C',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Coimbatore',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'AB83049D-5328-457C-AB20-C06C4F469AD9',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Komarapalayam',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ACB35BFD-6F5D-48F1-97EE-2F61AAC5EEE4',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Madurai',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'BBF265A2-9FB4-4375-BF91-AA1FAE4B4256',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Poonamalle',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'BD640D79-CB5D-4F88-B0CC-654203DA4DD9',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Tiruppur',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'BF592AF3-5313-4F32-BE61-4923F81EC9D2',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Colachel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'C44402F4-AD3F-4582-8278-976C31BB48DB',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Gudiyatham',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'CEACF63B-0344-4784-9F2B-9497E9E3A482',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Devakottai',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'D1489D7E-18FC-48DD-AD0A-BA41EACB9621',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Rasipuram',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'D8154CA5-0103-41CE-AC9D-6026DB06435D',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Tiruvarur',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'D909C2D9-7BAA-4AE9-BAB8-16FD01E1A4D4',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Vellore',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'DCD50046-F890-4A67-B6CA-BE5EFCED549F',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Srivilliputhur',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'E8C7D023-0DB4-4DEB-8C3D-B35AF4BEBCAC',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Tiruvallur',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'EAB5B136-BC6B-4CBA-99E9-A13A86DB7CCC',
    'vocabulary_machine_name' => 'municipality',
  );
  $terms[] = array(
    'name' => 'Krishnagiri',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'FF0AB27C-5236-4564-9C65-F7760E761280',
    'vocabulary_machine_name' => 'municipality',
  );
  return $terms;
}
